---
title: "Lab 2: What Makes a Movie Successful? Fall 2021"
author: 'w203: Statistics for Data Science'
date: "November 1, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2) 

library(sandwich)
library(stargazer)
```



```{r setup, include=FALSE}
d <- read.csv('./src/data/Clean_Data_set.csv')

actors <- read.csv('./src/data/Greatest Actors List.csv')

directors <- read.csv('./src/data/Greatest Directors List.csv')
```


```{r setup, include=FALSE}
summary(d)

short_data <- drop(d$dvd_release)


# exclude variables "production", "dvd_release", "imdbid", poster, keywords
myvars <- names(d) %in% c("production", "dvd_release", "imdbid", "poster", "keywords")
short_data <- d[!myvars]

```

```{r}
6 == 9
```



```{r}
final_table <- short_data %>% 
  mutate(
    comedy = case_when(
      #encode comedy, and all subsequent genres as binary
      regexpr('Comedy', genres) >= 0 ~ 1, 
      regexpr('Comedy', genres) == -1 ~ 0),
    
    drama = case_when(
      regexpr('Drama', genres) >= 0 ~ 1, 
      regexpr('Drama', genres) == -1 ~ 0),

    family = case_when(
      regexpr('Family', genres) >= 0 ~ 1, 
      regexpr('Family', genres) == -1 ~ 0),

    romance = case_when(
      regexpr('Romance', genres) >= 0 ~ 1, 
      regexpr('Romance', genres) == -1 ~ 0), 
    
    thriller = case_when(
      regexpr('Thriller', genres) >= 0 ~ 1, 
      regexpr('Thriller', genres) == -1 ~ 0), 
    
    animation = case_when(
      regexpr('Animation', genres) >= 0 ~ 1, 
      regexpr('Animation', genres) == -1 ~ 0), 
    
    adventure = case_when(
      regexpr('Adventure', genres) >= 0 ~ 1, 
      regexpr('Adventure', genres) == -1 ~ 0), 
    
    horror = case_when(
      regexpr('Horror', genres) >= 0 ~ 1, 
      regexpr('Horror', genres) == -1 ~ 0), 
    
    music = case_when(
      regexpr('Music', genres) >= 0 ~ 1, 
      regexpr('Music', genres) == -1 ~ 0), 
    
    crime = case_when(
      regexpr('Crime', genres) >= 0 ~ 1, 
      regexpr('Crime', genres) == -1 ~ 0), 
    
    sci_fi = case_when(
      regexpr('Science Fiction', genres) >= 0 ~ 1, 
      regexpr('Science Fiction', genres) == -1 ~ 0), 
    
    action = case_when(
      regexpr('Action', genres) >= 0 ~ 1, 
      regexpr('Action', genres) == -1 ~ 0), 
    
    war = case_when(
      regexpr('War', genres) >= 0 ~ 1, 
      regexpr('War', genres) == -1 ~ 0), 
    
    western = case_when(
      regexpr('Western', genres) >= 0 ~ 1, 
      regexpr('Western', genres) == -1 ~ 0), 
    
    fantasy = case_when(
      regexpr('Fantasy', genres) >= 0 ~ 1, 
      regexpr('Fantasy', genres) == -1 ~ 0), 
    
    foreign = case_when(
      regexpr('Foreign', genres) >= 0 ~ 1, 
      regexpr('Foreign', genres) == -1 ~ 0), 
        
    mystery = case_when(
      regexpr('Mystery', genres) >= 0 ~ 1, 
      regexpr('Mystery', genres) == -1 ~ 0), 
    
    history = case_when(
      regexpr('History', genres) >= 0 ~ 1, 
      regexpr('History', genres) == -1 ~ 0), 
    
    documentary = case_when(
      regexpr('Documentary', genres) >= 0 ~ 1, 
      regexpr('Documentary', genres) == -1 ~ 0),
    
    january = case_when(
      
      substr(release_date, start = 1, stop = 2) == '1/' ~ 1, 
      substr(release_date, start = 1, stop = 2) != '1/' ~ 0),
    
    
     february = case_when(
      
      substr(release_date, start = 1, stop = 2) == '2/' ~ 1, 
      substr(release_date, start = 1, stop = 2) != '2/' ~ 0),
    
    march = case_when(
      
      substr(release_date, start = 1, stop = 2) == '3/' ~ 1, 
      substr(release_date, start = 1, stop = 2) != '3/' ~ 0),
    
    april = case_when(
      
      substr(release_date, start = 1, stop = 2) == '4/' ~ 1, 
      substr(release_date, start = 1, stop = 2) != '4/' ~ 0),
    
    may = case_when(
      
      substr(release_date, start = 1, stop = 2) == '5/' ~ 1, 
      substr(release_date, start = 1, stop = 2) != '5/' ~ 0),
       
     june = case_when(
      
      substr(release_date, start = 1, stop = 2) == '6/' ~ 1, 
      substr(release_date, start = 1, stop = 2) != '6/' ~ 0),
    
    july = case_when(
      
      substr(release_date, start = 1, stop = 2) == '7/' ~ 1, 
      substr(release_date, start = 1, stop = 2) != '7/' ~ 0),
    
    
    august = case_when(
      
      substr(release_date, start = 1, stop = 2) == '8/' ~ 1, 
      substr(release_date, start = 1, stop = 2) != '8/' ~ 0),
    
    september = case_when(
      
      substr(release_date, start = 1, stop = 2) == '9/' ~ 1, 
      substr(release_date, start = 1, stop = 2) != '9/' ~ 0),
    
    october = case_when(
      
      substr(release_date, start = 1, stop = 2) == '10' ~ 1, 
      substr(release_date, start = 1, stop = 2) != '10' ~ 0),
    
    november = case_when(
      
      substr(release_date, start = 1, stop = 2) == '11' ~ 1, 
      substr(release_date, start = 1, stop = 2) != '11' ~ 0),
    
    december = case_when(
      
      substr(release_date, start = 1, stop = 2) == '12' ~ 1, 
      substr(release_date, start = 1, stop = 2) != '12' ~ 0)
    
    
  )
      
  
  
final_table
```




```{r}

ggplot(final_table, aes(x=budget)) + geom_histogram(bins = 100)

ggplot(final_table, aes(x=revenue)) + geom_histogram(bins = 100)


# The logarithm of both budget and revenue appear more homogenously distributed
ggplot(final_table, aes(x=log(budget))) + geom_histogram(bins = 100)

ggplot(final_table, aes(x=log(revenue))) + geom_histogram(bins = 100)

ggplot(final_table, aes(x=runtime)) + geom_histogram(bins = 100)
#runtime appears to be relatively normally distributed overall, except for the narrow group on the lower end of time


#ggplot(final_table, aes(x=release_date)) + geom_bar()


ggplot(final_table, aes(x=substr(release_date, start = 1, stop = 2))) + geom_bar()
#Release date overall looks fairly well distributed over time - the number indicates month, with 1/ - 9/ representing  January to September, and 10 - 12 representing October - December


```

```{r}

plot(log(final_table$budget), log(final_table$revenue))
title(main = 'Logarithmic Movie Revenue over Budget', xlab = 'Log of Budget', ylab = 'Log of Revenue')
# The shape of the relationship looks to be positively correlated, and seems to suggest that a higher budget results in a higher revenue

plot(final_table$runtime, log(final_table$revenue))
title(main = 'Logarithmic Movie Revenue over Movie Runtime', xlab = 'Runtime', ylab = 'Log of Revenue')

```


